# -----
# @file          : cell_loc.tcl
# @project       : OpenPARF
# @author        : Jing Mai <jingmai@pku.edu.cn>
# @created date  : July 25 2023, 20:44:04, Tuesday
# @brief         :
# -----
# Last Modified: October 13 2023, 14:52:14, Friday
# Modified By: Jing Mai <jingmai@pku.edu.cn>
# -----
# @history :
# ====================================================================================
# Date         	By     	(version)	Comments
# -------------	-------	---------	--------------------------------------------------
# ====================================================================================
# Copyright (c) 2020 - 2023 All Right Reserved, PKU-IDEA Group
# -----
# This header is generated by VSCode extension psi-header.
#

# open_checkpoint routed_design.dcp

set output_file [open "cell_loc.csv" "w"]

set all_cells [xilinx::designutils::get_leaf_cells *]

puts $output_file "NAME,REF_NAME,LOC,BEL"
foreach cell $all_cells {
    set cell_name [get_property NAME $cell]
    set cell_refName [get_property REF_NAME $cell]
    set cell_loc [get_property LOC $cell]
    set cell_bel [get_property BEL $cell]
    puts $output_file "$cell_name,$cell_refName,$cell_loc,$cell_bel"
}

close $output_file