/*
 * @file          : mixed_abacus_legalizer.h
 * @project       : OpenPARF
 * @author        : Jing Mai <jingmai@pku.edu.cn>
 * @created date  : July 19 2023, 16:55:18, Wednesday
 * @brief         :
 * -----
 * Last Modified: July 20 2023, 15:06:25, Thursday
 * Modified By: Jing Mai <jingmai@pku.edu.cn>
 * -----
 * @history :
 * ====================================================================================
 * Date         	By     	(version)	Comments
 * -------------	-------	---------	--------------------------------------------------
 * ====================================================================================
 * Copyright (c) 2020 - 2023 All Right Reserved, PKU-IDEA Group
 * -----
 * This header is generated by VSCode extension psi-header.
 */
#ifndef OPENPARF_OPS_MIXED_ABACUS_LG_SRC_MIXED_ABACUS_LEGALIZER_H_
#define OPENPARF_OPS_MIXED_ABACUS_LG_SRC_MIXED_ABACUS_LEGALIZER_H_

#include "database/placedb.h"
#include "util/torch.h"
#include "util/util.h"

OPENPARF_BEGIN_NAMESPACE

namespace mixed_abacus_legalizer {

void mixedAbacusLegalizerForward(database::PlaceDB const &placedb,
        at::Tensor                                        pos,
        at::Tensor                                        lg_inst_ids,
        int32_t                                           area_type_id,
        at::Tensor                                        shape_inst_map_bs,
        at::Tensor                                        shape_inst_map_b_starts,
        at::Tensor                                        shape_inst_map_b2as,
        at::Tensor                                        region_inst_map_b2as,
        at::Tensor                                        region_boxes);

}   // namespace mixed_abacus_legalizer

OPENPARF_END_NAMESPACE

#endif   // OPENPARF_OPS_MIXED_ABACUS_LG_SRC_MIXED_ABACUS_LEGALIZER_H_
