/*
 * @file          : mixed_abacus_legalizer_pybind.cpp
 * @project       : OpenPARF
 * @author        : Jing Mai <jingmai@pku.edu.cn>
 * @created date  : July 19 2023, 16:55:18, Wednesday
 * @brief         :
 * -----
 * Last Modified: July 21 2023, 16:24:54, Friday
 * Modified By: Jing Mai <jingmai@pku.edu.cn>
 * -----
 * @history :
 * ====================================================================================
 * Date         	By     	(version)	Comments
 * -------------	-------	---------	--------------------------------------------------
 * ====================================================================================
 * Copyright (c) 2020 - 2023 All Right Reserved, PKU-IDEA Group
 * -----
 * This header is generated by VSCode extension psi-header.
 */
#include "mixed_abacus_legalizer.h"

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("forward", &OPENPARF_NAMESPACE::mixed_abacus_legalizer::mixedAbacusLegalizerForward,
          "Mixed Abacus Legalization forward");
}
